# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffcd74a85a50d8564599fb640dc2e75865314afad8d137549a1814594dc5235dd489a2dcd19d8750e113b1b84580bbe3ea622e2730a9f615900e54ce72a36ab

test:
  secret_key_base: 53f6cb54959357c86655fae794d68cd32ce8094978515d8bd70c9f973637329d6f1fd6094c22920da7a7487efef939817e1392eaee200c9187ce032c8dc866d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
